---
title: "surveyreport TODO"
author: "Stephan Daus"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    df_print: tibble
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Main steps
- Split off MplusAutomation extentions
- Split off janitor tabyl extensions (which should be split itself into janitor and tabyl)
- Split off read_surveyxact to separate package (for reading in surveymonkey, etc)
- Split off rename_variables into either janitor or a vctrs::vec_as_names() extension
- Push SX to export proper formats. Move to Qualtrics or Nettskjema
- Graph related stuff into existing graph package? Or tidySEM, etc?




## infoframe returns data frame with items (rows) and diagnostics (columns)
	Improvement over time (p1-p0)
	IRT parameters (a, b, c), with low discriminators, and extremely hard/easy items flagged
	Items with responses above/below 95/5 percentage flagged
	Low CFA loadings
	Loadings improved if item removed
	
# Overall design
-	User should be allowed to add arbitrary number of special barcharts, captions, etc. So each adder should have a suffix-labelling argument.
-   Each of the add_ functions should call an underlying hidden function that generates the specified output for a single case, and the add\_\* function will loop across all rows in the design frame with purrr::pmap() and attach the output using a standard helper function. Then an autoreport-function could do looping itself by only calling underlying functions
-   S3 class-based objects, or just lists for now? input/output as list of df, var_frame and design_frame. Single input, single output.
-   Avoid :: by @importFrom pkg fun to save evaluation time
-	Ensure output of obj always contain tibbles
-   missing() instead of is.null() for arguments?
-   WIth the "create_entry" functions that take x_var, y_var, ..., These should be prefixed with a dot internally to avoid conflict if the user has added columns that are named with variables that happen to be used internally.
-   If you return the same type of output from multiple functions, you should create a function that consistently creates exact the same format (to avoid accidental inconsistency), and consider making it an S3 class (so you can have a custom print method).
-   Prepare an example infoframe object to simplify examples.
- Providing argument with scoring key to test items provides descriptives for answer choices, and then later scores before analyses
-	Merge add_caption and add_interpretation to a more generic add_text?
-	verbose = FALSE
-	na_rm = TRUE
-	https://github.com/tidymodels/model-implementation-principles/blob/master/06-arguments.Rmd
-	Make generalisert TIC, theta, item thresholds-grafmaker som tar mirt, MplusAutomation, lavaan, TAM, etc)


# rename_vars_by_label()
-   Rename variable names in df_data to match labels? Then original var names don't matter.

# step_auto_tick_recode

-   Some form of automatic recode of multiple tick-box items where no cross is missing? Or perhaps strongly advice people not to use them?

# create_infoframe
-   Better tests and better diagnostics if tests fail: 
-   Replace separators with patterns? Or character vector patterns? First letters before numbers? 
-   The check of corresponding group and group_label should rather be checking if all groups have the same group_label, not the other way around
-	add_y_indicators argument so one can drop single-item analyses if one is only interested in constructs.


# add_percent

# add_regression

-   Extract dummy recoder?
-   loading_cutoff =\> move to add_fit?
-   V2: How to distinguish x_var as single latent variable from set of manifest variables?
-   Improve extraction of errors in MplusAutomation::readModels(). New separate function: Extract variables that are failing
-   V2: Rerun without poor variables if NDependent\>4: toupper(colnames(rdata)). Separate function to work on output dataframe.
Warning messages:
1: Unknown or uninitialised column: `x_var`. 
2: Unknown or uninitialised column: `x_var`. 
3: Unknown or uninitialised column: `x_type`. 
4: Added parts that were missing in design_frame: x_var,x_group,x_ref_cat 
## run_model

## prepare_mplus_model

## extract_mplus_model
-   Make into broom tidier? Though will be of limited use.
-   cronbach, mcdonald_omega? Or using psych::alpha

## prepare_lavaan_model

# add_meaning
-	Incorporate all the below as glue strings. 
-	latent_diff, construct_fit, effect, percent, univariate
-	instead of tolower, only change first letter of sentence.
-	V1: Template sentences for fit.
-   V2: Text reporting: Adding adverbial clauses to spice up: If contrast to previous finding.
-   V2: Text reporting: Summarize findings if all of the same pattern (X positively correlated with all of Y1, Y2, Y3, ... and detailed=FALSE)
-   V2: Distinguish between first-time mention of a variable within a section (where full x_label is mentioned "Vi finner for x_label at...)
-	V2: What to do for the "else"-category, those not matched? Leave to user to specify a catch-all regex?
-   V2: Get someone to translate template sentences to English, German, Nynorsk, etc.

# add_percentbar_mschart
-	Colours are not correct if first category in the first variable is completely missing, at least in Tett på realfag, "I hvilken grad benytter du deg av følgende undervisningsformer i naturfagundervisningen"
-	If a single variable plot only uses 3 categories, but there are actually 5 in the battery, how to ensure that the right ones are used.

# add_rangeplot_chart, add_forest_chart, add_bivariate_chart

# create_report
-   vctr::vec_assert
-	Split up function into minor parts, preferably finding some R6 solutions.
-	remove_empty_y_var should remove empty y_var if TRUE
-	officer::body_add_caption(value = officer::block_caption())
-   If first variable in a y_var has no response in a category, category order is messed up.
-   Sorting of variables both within section, but also within a graph/table!
-   Make function general enough so that it can be used in a pmap-loop for school reports. section1_new_file=TRUE for school reports
-   Make tables in doc prettier (header formating, left align first column, etc)

# omitted_recoder_df
-	return tibble if input tibble
-	keep labels

### Version 2.0

-   Scatter+trend line plots for linear/binary logistic regression models where x_focus is specified
-   Forest plot for regression model results
-   Same plots for ggplot2 as for mschart
-   Method chapter: response rate (opened/completed), broken down by x_var, representativeness given pop_var, map for gsiid
-   Also export Rmarkdown/html-file?

### Modify xml-files:

-   Hide axis titles.

-   Right-align axis text by modifying xml-raw data

-   Drop data labels if smaller than 5%

-   Insert this: dLbl\><c:idx val=X_value/><c:delete val="1"/><c:extLst><c:ext uri="{CE6537A1-D6FC-4f65-9D91-7224C49458BB}" xmlns:c15="http://schemas.microsoft.com/office/drawing/2012/chart"/><c:ext uri="{C3380CC4-5D6E-409C-BE32-E72D297353CC}" xmlns:c16="http://schemas.microsoft.com/office/drawing/2014/chart"><c16:uniqueId val="{00000000-BC21-437A-B275-29C6E34D2EC4}"/></c:ext></c:extLst></c:dLbl>\<c:

-   After this: </a:srgbClr></a:solidFill></a:ln><a:effectLst/></c:spPr><c:invertIfNegative val="0"/><c:dLbls>\<c:

-   Strip off all unnecessary dependencies

-   Documentation

-   Excel template

### out of my control:

-   Excel output, table and chart into Excel
-   Crashes if file is open (<https://github.com/davidgohel/officer/issues/349>)
-   Also file doesn't open if a crashed Word app is open...
-   Non-ASCII letters (<https://github.com/ardata-fr/mschart/issues/57>), but workaround works.

# create_report_grouped

-   group-specific reports with automatic email sending

# utils

## assert_options
- Takes obj, not design_frame?

# print2.rdocx
-   replace utils::zip with officer::unpack_file

## add_element

## loop across (basically just a wrapper to purrr::pmap)

# create_psychometrics_report

-   Standard set with functions to conduct psychometric analysis. Summarizes models from various packages, and presents according to common objectives:
-   TODO: Should split into functions fitting into the tidymodelverse. This requires brooming TAM, mirt, CDM, sirt, lavaan, MplusAutomation, etc.
-   Aims:
-   single function to retrieve information on item-specific descriptives
-   single function to retrieve information on which items are likely worst fitting for unidimensional scale
-   single function to retrieve information comparing various models (uni, bi/multidimensional, correlated, second order, etc)

\*\* Versjon 0.3 \* Endre filnavnet \* argument: Velge hvilke funksjoner som skal kjøres \* argument: Velge hvilke IRT-modeller som skal kjøres (1PL, 2PL, etc) \* funksjon: Trekke ut Wright-map plot som egen funksjon (plot_1a) \* funksjon: Trekke ut ICC plots-loopen for TAM-data, som eegen funksjon \* funksjon: Trekke ut Mplus-modeller som egne funksjoner \* Generalisere mer (særlig grafer) og unngå hardkodede variabelnavn/labels \* Be Alexander Rorbitzh om å kunne endre navn på Plots-mappe \* argument: Endre argument defaults til engelsk/tom \* funksjon: Legge inn fortolkninger som tekst i fit (høy infit, etc). \* funksjon: Item information curves (all in one graph)

-   Bedre struktur på returnert objekt: alle rå-objekter i egen liste (raw). Input i egen liste (input), Alt nyttig i egen liste (\$summary)

-   summary\$mod: tibble, rader=modell, kolonner= person abilities mean, item spread, C alpha, CFA, TLI, RMSEA, SRMR, faktorladningsspredning,

-   summary\$tam_1pl: tibble, rader=item, kolonner=item difficulty, discrimination, outfit, infit, item information curve summary?,

-   funksjon: Excel-output av alt i \$summary-listen, inkl Chart-grafer?.

-   Lage/finne en oppskrift på hele valideringsprosessen, basere output rundt dette.

-   Legge inn flere pakker?

-   Mer om DIF/MI, local independence, Q3, etc

-   Bifaktor/second order-struktur?

-   Når andre pakker er oppdatert (ASCII), fjerne noen endringer av tittel, etc.?

-   Tidyselect?

-   Kontroller og Feilmeldinger (rlang)

# Examples and documentation

# Other

parsnip, broom, yardstick extensions for SEM models: <https://www.tidymodels.org/learn/develop/models/> and <https://www.tidymodels.org/learn/develop/broom/> and <https://www.tidymodels.org/learn/develop/metrics/> easystats extensions (or not, as they don't yet support tidymodels) workflow-package extensions parsnip, and returns broom, yardstick)



# Gamle notater, kan være noen ideer verdt å beholde her
#############################################################################
#### Sett med funksjoner for rask høykvalitetsanalyse av spørreskjemadata ####
2	Få Rambøll til å legge til kolonnenavn på Labels.csv

# NIFUstolper: Produksjon (direkte lagring til disk) av stolpediagrammer for spørsmålsbatterier gruppert etter supergrupper, grupper, osv og brutt ned på liste med brytningsvariabler
1	Unngå overskriving: Legg til siffer, sjekk på nytt, etc.
1	Algoritme for høyden (minste størrelse når strip-tekst går over flere linjer)
2	SVG eller vektorgrafikk i Word
2	facet-tekst justeres slik at den aldri forsvinner om den blir for mange linjer
2	Sjekk at det er færre verdier enn farger

# Produksjon av alle mulige tabeller for sett med variabler brutt ned på liste med brytningsvariabler, fordelt på batteri
1	function(. data, .outcome_vars=TIDY SELECT list.vars_break=NULL, .vars_break2=null, brytning_ved_rader=T,  batteri_var="")

# Tekstgenerering av signifikanstester for sett med ordinale variabler brutt ned på liste med brytningsvariabler.
1	Fikse feil når det er flere grupper som sammenlignes (N og m= synes å være samme for 1. og 3. oppføring?
1	Lagre analysen per variableGroup - altså en ytterloop - kontinuerlig
1	Raskere, går tregt
2	Sortere gruppene etter faktor-levels, eller etter hva som er høyest.
1	Lagre krysstabeller i samme slengen. Setningen kan legges umiddelbart under tabellen.
2	Legge til totalen for å sammenligne gruppene med totalen, men er dette fortsatt uavhengige grupper? (add_total=T)
1	ta sjekk på om ordinalvariabel er ordered factor, gi informativ feilmelding
1	Sjekk om variabler inneholder NA, fjerne med advarsel
2	unngå coin-pakken, finne referanser til metoden (Agresti, 2007)
3	Hvilke grupper har høyest/lavest verdi, på hver variabel?
2	Andre ikke-parametriske distribusjoner (nominal-nominal, binær, interval, etc)
3	Omnibus-tester?
3	Ulike type fraser for ulike batterier (enten character vector of length 1 or character vector =length(unique(variableGroup)
3	Randomisere mellom fraser
	compareGroups-pakken?
	Bør også eksportere som CSV-fil resultatene da det kan være letter eå lese. "mer enig enn" kan da bli > eller <.

# NIFU_efa: EFA av alle utfallsvariabler
	Finner selv ut hvor mange faktorer er teoretisk mulige
	Fjerner iterativt variabler med missing over 20%, forenkler variabler med mindre enn 10% per kategori 
	en egen variabel i Structure forteller hvilke som skal snus i faktoranalyser
	om ikke MplusAutomation oppdateres: kjører ESEM for å hente ut faktorladningene
	Kobler på variableQuestion og variableGroup
	Sorterer slik at sterkeste faktorladningene kommer først
	Fjerner alt mellom -.4-.4 og omrokkerer faktorene
	Printer ut i Excel, fargelegger
	Legger ved rå (Spearman) korrelasjoner i eget regneark

# analyze_psych: Psykometriske analyser av konstrukter
	CFA for hvert spørsmålsbatteri og spørsmålsoverbatteri, m/alpha, CFA, TLI, RMSEA, SRMR, faktorladningsspredning, osv
	Measurement invariance for hver av brytningsvariablene
	Lager en samletabell for alle variableGroup
	Optional item-nivå info, DIF, etc

Rapportere bug til Mplus om at $1 blir kuttet vekk fra CI-output.
Rapportere bug til MplusAutomation: LOGISTIC REGRESSION ODDS RATIO RESULTS kommer ikke med 

# Tekstgenerering av Mplusmodeller
	Total, så hver spesifikk indirekte, innenfor disse vise deleffektene, så total indirekte, så direkte.
	Benytter STDYX og STDY avhengig av type variabel

# Automatisk generering av hvert av det ovenstående for hvert batteri (samlefunksjon) i et Word-dokument med NIFU-template, gruppert etter headings, 
3	Legger inn grafene, tabellene, signifikanstester, m.m. under korrekt overskrift.
	Må sortere riktig. Hm
	Må ha et register i CSV-fil eller lignende med fraser man kan benytte til variasjon, for introduksjon av grafer, tabeller, osv.
	
